### ISSUE TITLE
D3-05 · Retention / evidence clock

### ISSUE THREAD

**Issue by thopatevijay** [thopatevijay/saakshi#28]
**Ticket** `D3-05` · **Milestone** Day 3 — Differentiators · **Estimate** 2.5h

## Context

**The most departmentally useful feature in the whole build, and nearly free.**

The problem statement states retention is *"7 days ... others for 15 days or more"* and varies by
department. So evidence silently expires. Report a crime on day 12 and **nobody in Gujarat can tell
you what footage still exists.** An investigating officer's most urgent question is "what can I still
get, and how long do I have?" — and today there is no way to answer it.

## Scope

- Given a location + radius + time window: which cameras covered it, and for each — is that footage
  **still within retention**, and when does it expire
- Countdown per camera: days/hours remaining, derived from `cameras.retention_days` per department
- Three states: `available` · `expiring soon` (configurable threshold, default 48 h) · `expired`
- **Preservation request** workflow: officer flags footage to preserve → request recorded with case
  reference → audited → appears on a preservation queue. (We cannot actually extend a department's
  retention; we generate the actionable request and record it. **Be explicit about that limit.**)
- Surfaced in three places: the alert detail ("this evidence expires in N days"), the trace view
  (per sighting), and a standalone "evidence availability" search
- Estate-wide view: how much of the estate is on 7-day vs 15-day vs longer retention, by department

## Acceptance Criteria

- [ ] Location+time query returns covering cameras with correct retention state
- [ ] Countdown arithmetic correct across day boundaries and DST-free IST; boundary tests present
- [ ] Cameras with unknown `retention_days` reported as **unknown**, never assumed
- [ ] `expiring soon` threshold configurable
- [ ] Preservation request records case reference, is audited, and appears on the queue
- [ ] The UI states plainly that a preservation request is an *instruction to the owning department*,
      not an automatic retention extension
- [ ] Retention state shown in alert detail and trace views
- [ ] Estate-wide retention distribution matches a hand-checked SQL count

## Deliverables

- `packages/api/src/services/retention.ts`
- `packages/web/app/evidence/*` + retention badges in alert and trace views
- `docs/retention-model.md` — the model, the honest limits, and what the department must do

## Validation Gate

```bash
npm run test -w packages/api -- retention
curl -fsS "localhost:4000/api/v1/evidence/availability?lat=23.2&lon=72.6&radius_m=500&at=2026-09-01T14:00:00Z" | jq
psql $DATABASE_URL -c "select retention_days, count(*) from cameras group by 1 order by 1;"
```

- [ ] Boundary tests green
- [ ] Unknown-retention cameras reported as unknown
- [ ] Screenshot for the deck

## Handoff → D4-04

Frame this in the deck as an *investigation* feature, not a storage feature. That is how a police
audience will hear it.

**Comment by thopatevijay** [comment]
**Blocked by:** #10

Do not start this ticket until every blocker is closed. Verify with `/status` or `gh issue view <n>`.

**Comment by thopatevijay** [comment]
### ⚠ Blocker note from D1-08 (#12) — read before starting

**1 · The geolocated set and the measured set are disjoint. You must decide the same question D1-08 did.**

| set | n | coordinates | trust score |
|---|---|---|---|
| `cam01`–`cam30` (sandbox catalogue) | 30 | **none** — `location IS NULL` for all 30 | **real, measured** |
| `GJ-*` (`fixtures/cameras-bulk-sample.csv`) | 50 | real Gujarat lat/lon | **none** — not real streams |

The upstream catalogue is a bare `[{id,name}]` array, so it publishes no coordinates (D1-04 measured
this: *"Every `declared_*` column is therefore NULL"*). **The cameras anybody has actually measured
are exactly the ones that cannot be placed on a map.** Silently dropping either set is the failure
mode: invisible measured cameras, or geolocated cameras presented as if they had been assessed.

D1-08's answer, for consistency: a map pane for everything with coordinates, plus an explicit
**"Not on the map · N"** tray listing the unplaced ones with their real band chips, both counts on
screen at all times. Reuse the tray pattern rather than inventing a second answer.

**2 · Take the band from the API. Never `trust_score >= 70`.**

`CameraResponse` now carries two additive fields (D1-08, no migration):

```ts
band: 'trusted' | 'degraded' | 'untrusted' | 'dead' | null   // null = never probed
catalogueStatus: 'active' | 'absent'
```

`band` is resolved server-side from the **latest health check's** `connectable`, because an
unreachable camera keeps its last good score — arithmetic on the stored number paints a camera that
went dark yesterday green. `band: null` means never probed and must render differently from a low
score (D1-08 uses a hollow ring — a different *shape*, not a paler shade). Colours live in one place:
`packages/web/src/lib/registry/trust.ts` — `BAND_STYLE`, `bandKeyOf()`, `bandFillExpression()`.

**3 · The map component already takes an overlay.**

`RegistryMap` (`packages/web/app/(shell)/registry/registry-map.tsx`) takes a plain GeoJSON
`FeatureCollection` and owns nothing about how it was built:

```ts
data: CameraFeatureCollection      // from toFeatureCollection() in src/lib/registry/geojson.ts
selected: string | null            // camera id → the `selected-halo` layer
onSelect: (id: string | null) => void
onViewportChange?: (bbox: string) => void   // debounced 350 ms, "minLon,minLat,maxLon,maxLat"
initialBbox?: string | null
```

Layer ids in draw order — **insert an overlay before `'clusters'` so camera pins stay on top**:
`background · earth · landcover · landuse · water · water-line · roads-{minor,medium,major} ·
boundaries-{country,state,disputed} · place-{city,neighbourhood} · clusters · cluster-count ·
selected-halo · camera-pins`.

Source `cameras` is clustered (`clusterMaxZoom: 11`, `clusterRadius: 46`, `promoteId: 'id'`). **A
route line or a coverage polygon must be its own source and layer**, added on `map.on('load')` — do
not merge geometry into `cameras`, or the cluster counts stop meaning "cameras".

**4 · Basemap constraints.**

Self-hosted PMTiles: bbox `68.0,19.9,74.6,24.8`, **z0–12 only** (asking for z13 gets 404s, not
detail), 28 MB, gitignored, rebuilt with `./scripts/build-basemap.sh`. Glyphs are vendored for
**Latin and Latin Extended-A only** (`Noto Sans Regular` / `Noto Sans Medium`, ranges `0-255` and
`256-511`) — Gujarati and Devanagari labels are *not* renderable, so every label layer reads
`name:en` with `name` as the fallback. **`packages/web` is pinned to `maplibre-gl@^5`**: v6 cannot
find its worker under webpack and fails as a silently blank map. See `docs/basemap-setup.md`.

**5 · Debug handles to reuse, not remove.**

`window.__saakshiMap`, `window.__saakshiFeatures`, `window.__saakshiMapIdle`,
`window.__saakshiMapErrors`. A WebGL canvas is opaque to assertions; these are how
`packages/web/scripts/verify-map.mjs` checks feature coordinates against `psql` and times frames
during a pan. The CDP helper is `packages/web/scripts/cdp.mjs` — copy the pattern rather than adding
a browser-automation dependency.

**6 · `cameras.status` is still single-valued.** Every camera reads `unknown`; nothing writes that
column. Drive any health dimension from the trust band, not from `status`. Logged to `BL-01`.

**Comment by thopatevijay** [comment]
### ⚠ Blocker note from D2-02 (#16 · PR #56) — read before starting

**The evidence object store exists now.** `docs/evidence-store.md` is the full contract; the parts
that will bite if assumed wrong:

**`sightings.crop_uri` holds `s3://<bucket>/<key>`, not a URL.** A signed URL is a credential with an
expiry — persisting one would put a value in the database that stops working, and an export bundle
would ship a dead link. Mint at read time, synchronously and with no network call:

```ts
import { evidenceStoreFromEnv } from '../services/evidence.js';
const store = evidenceStoreFromEnv();                 // null when MINIO_* unset — degrade, never throw
const key = cropUri.replace(/^s3:\/\/[^/]+\//, '');
const url = store?.presignGet(key, 900);
const bytes = Buffer.from(await (await fetch(store!.presignGet(key, 60))).arrayBuffer());
```

**The pre-signed URL is signed for GET only** — `curl -I` / a HEAD request returns 403, because the
HTTP method is part of the SigV4 canonical request. Verified against the aws-cli's own presigner, so
it is S3 semantics, not our code. Never gate on `curl -fsSI "<signed-url>"`.

**Path convention:**

```
evidence/<camera EXTERNAL id>/<yyyy-mm-dd>/<sighting uuid>-{vehicle,plate}.jpg
```

The date is the **sighting's** UTC date from its PTS-derived `ts`, never the upload date — a crop
that lands at 00:04 for a vehicle seen at 23:58 retains under the day it was *seen*. The camera
segment is the external id (`cam01`), not the uuid.

**`store.listObjects(prefix)` follows continuation tokens** and returns every key with its size — it
does not stop at 1,000.

**Retention lives on the bucket, not in Postgres.** `store.getRetention()` returns the rules the
store itself reports — today `evidence/` 15 days and `evidence/watchlist/` 90 days, from
`config/evidence-retention.json`, applied by `npm run evidence:retention`. It survives a `db:reset`
but **not** a MinIO volume wipe; re-apply after one or the read-back is empty for reasons unrelated
to any code. `evidence/watchlist/` is reserved and currently empty — D2-05/D2-06 own it.

**Only best shots have a crop:** ~1 sighting in 30 (measured 838 of 25,367). `where is_best_shot`.

**Storage figures are PROVISIONAL and marked as such in `docs/evidence-store.md` §7.** Measured mean
crop **2,912 B**, **96,214 B ≈ 94.0 KiB per 1,000 sightings**, from a labelled replay of the D0-01
recon stills on 682×384–1536×864 frames (median box long edge 75 px) — the sandbox gateway semaphore
was held by another ticket during the wave. A 1080p live feed will be larger. **Do not rewrite
PROJECT.md §9's 15 KB/crop to 2.9 KB**; the honest range is 3–15 KB pending a live-feed measurement,
which is one command once the gateway is free.

**The figure that is not provisional is 33.0 crops per 1,000 sightings** — best-shot selection
removes ~97% of the crops a naive design would store. That ratio is a property of the tracker and the
selector, not of the frame size, and it is the storage argument the deck should make.

**Colour is honest, including where it fails** (`docs/evidence-store.md` §8): 10.9% of reads refused
overall — 6.4% in daylight against 21.5% and 24.0% on the two dimmest recon slots. `vehicle_color`
may be the literal string `'unknown'` with `attributes_low_confidence` set; that is a refusal, not a
missing value, and must never be rendered as an observation. Two-wheeler colour reads look confident
and are unreliable (the box is mostly rider). No accuracy claim against ground truth is made
anywhere, because there is no labelled colour ground truth for this estate.

**Comment by thopatevijay** [comment]
## Started D3-05 · Retention / evidence clock

**Branch** `feat/d3-05-retention-clock-05-09-2026` · **Started** 2026-09-05 · base `8ca3a1e` (main tip, after D3-07)

### Inherited handoffs read
- **#10 (D1-06, blocker — closed):** bands come from the API, prefer trends over single checks. Its
  transferable finding for this ticket is the one about gates: *the `curl` commands in these gates
  predate the RBAC matrix*, so `curl -fsS localhost:4000/api/v1/...` 401s without a bearer token.
  Expect the same here and record the real output with a token rather than weakening auth.
- **#27 (D3-04):** `writeAudit(db, principal, {...})` inside the transaction that made the change;
  `audit_log` has `seq` and `UNIQUE (prev_hash)`. A preservation request is an auditable act and goes
  in **that** chain — no parallel audit table.
- **#24 (D3-01):** OSRM on host port 5050 locally; not load-bearing for this ticket.
- **#12 (D1-08) / #16 (D2-02):** never persist a signed object-store URL; the placed set and the
  measured set are disjoint, and the answer is an explicit tray, never a silent drop.

### Assumptions (challenge these if they are wrong)
1. Retention is a **rolling window** on the recorder: footage at `t` is overwritten at
   `t + retention_days × 24 h`. IST is DST-free, so "+24 h" and "+1 calendar day" are the same
   operation — which is precisely why the AC names it.
2. `retention_days IS NULL` means *the department never told us*. It is `unknown`, never defaulted.
3. A camera with no coordinates cannot be shown to have covered a place. It goes in an explicit
   **unassessable** tray with its retention state still computed — D1-08's tray pattern, not a drop.
4. Coverage is "within radius of the point". `camera_coverage` is not populated for this estate, and
   claiming a view-frustum model we cannot compute would be an over-claim.

### Measured before writing any code
```
saakshi_d3_05=# select retention_days, count(*) from cameras group by 1 order by 1;
 retention_days | count
----------------+-------
                |    30      ← all NULL
saakshi_d3_05=# select count(*), count(location) from cameras where deleted_at is null;
 30 | 0                      ← none placed
```
**Every camera in the Gujarat sandbox estate publishes neither a location nor a retention period.**
That is not a gap in this ticket, it is the ticket's own thesis measured: nobody can currently answer
"how long does this footage last" because the catalogue does not say. It will be reported as
`unknown` throughout and stated plainly in the docs and on screen.

### Plan
1. `packages/shared/src/retention.ts` — the pure clock. Four states (`available` · `expiring_soon` ·
   `expired` · `unknown`), IST calendar presentation, boundary-tested. One source for API and web.
2. `packages/api/src/services/retention.ts` — coverage query (PostGIS `ST_DWithin`), estate-wide
   distribution, preservation-request create/list.
3. Migration **0020** `preservation_requests` — case ref, window, snapshot of the retention that
   applied, and the hash of the audit-chain entry that authorised it. Audited via D3-04's
   `writeAudit`, inside the same transaction.
4. `packages/api/src/routes/retention.ts` — `/api/v1/evidence/availability`,
   `/api/v1/evidence/retention/summary`, `POST|GET /api/v1/evidence/preservation`.
5. Retention badges on the alert view and per sighting on the trace view; a standalone
   `/evidence` screen with the estate distribution and the preservation queue.
6. `docs/retention-model.md` — the model, the arithmetic, and the honest limit: **a preservation
   request is an instruction to the owning department, not an automatic retention extension.**
   SAAKSHI does not control any department's recorder and will not imply that it does.

**Comment by thopatevijay** [comment]
## Handoff → D3-06, D3-GATE, D4-01, D4-03, D4-04, D4-05

### The endpoints

```
GET  /api/v1/evidence/availability      registry:read
       ?lat= &lon= &radius_m= [&at=] [&expiring_soon_hours=] [&department_id=]
     → { query, coverageModel:'proximity', coverageModelNote, covering[], unassessable[],
         counts:{covering, unassessable, byState, truncated}, legend, disclaimer }

GET  /api/v1/evidence/retention/summary registry:read
     → { totalCameras, declared, undeclared, shortestDeclaredDays, longestDeclaredDays,
         buckets[{retentionDays|null, cameras}], byDepartment[], located, unlocated, disclaimer }

POST /api/v1/evidence/preservation      registry:write   (an auditor deliberately cannot)
       { cameraId, windowStart, windowEnd, caseRef, purpose, notes? }
     → 201 { request, auditHash, disclaimer }

GET  /api/v1/evidence/preservation      registry:read
       [?status=] [&case_ref=] [&camera_id=] [&limit=] [&expiring_soon_hours=]
     → { data[], limit, counts:{open,acknowledged,preserved,declined}, disclaimer }
```

`caseRef` is `min(3).max(64)`, `/^[A-Za-z0-9/\-_.]+$/` — **the same shape D3-04 enforces on an export
case ref.** `purpose` is `min(3).max(500)`. Both mandatory on a preservation request. `radius_m` is
capped at **20 000**; the covering set is capped at **500** with `counts.truncated` saying so.

### `RetentionStatus` — the shape now on cameras, sightings and alerts

```ts
{
  state: 'available' | 'expiring_soon' | 'expired' | 'unknown';
  retentionDays: number | null;      // null = the department declared none. NEVER defaulted.
  expiresAt: string | null;          // ISO; null iff state === 'unknown'
  remainingMs: number | null;        // negative once expired
  remainingDays: number | null;      // magnitude; the sign lives on `state`
  remainingHours: number | null;     // 0-23, within the final day
  expiringSoonHours: number;         // the threshold this was judged against
  computedAt: string;                // a status is a snapshot and it says when
  expiresOnIstDate: string | null;   // 'YYYY-MM-DD', IST
  label: string;                     // '4d 6h left' | 'expired 2d 3h ago' | 'retention not declared'
}
```

**Never re-derive `state` from `expiresAt`.** Take it from the payload, the way D1-08 takes `band`
from the API. `packages/web/src/lib/evidence/retention.ts` is the single source for colour and
phrasing (`RETENTION_STYLE`, `RETENTION_SORT`, `evidenceClockSentence`), and its test asserts no
threshold arithmetic has leaked into the UI layer.

### ⚠ Breaking-ish: three response shapes gained a field

- `GET /api/v1/alerts` and `GET /api/v1/alerts/:id` now return **`AlertWithRetention`** —
  `AlertRecord` plus `retention: RetentionStatus | null`.
- `GET /api/v1/trace` — every entry in `sightings[]` gained `retention: RetentionStatus`.
- `packages/web`'s `TraceablePoint` gained `retention`, and the alert queue's `AlertRecord` type is
  now `AlertWithRetention` (`@saakshi/shared`).

**`retention: null` on an alert means "not computed on this delivery path", not "unknown
retention".** The list and detail always populate it; the **live SSE frame does not** — that path is
fed by the engine at raise time and does not read the registry, and an alert seconds old is by
construction at the far end of whatever window applies. The clock arrives with the next list read.
An undeclared period is `state: 'unknown'` **inside a present object**, and the two stay
distinguishable.

**If you parse an alert with zod on the web side, use `AlertWithRetention`, not `AlertRecord`.**
`z.object` strips unknown keys, so parsing against the unextended record drops `retention` silently
and nothing fails.

### ⚠ The alert clock is timed from the alert's FIRST sighting, not its last

`alert.ts`'s `ts`, not `lastSeenAt`. The oldest footage the alert covers is the first part of it to be
overwritten; timing from `lastSeenAt` would report an alert as safe while the approach — usually the
useful part — had already gone. Same rule on a preservation request: its clock runs from
`window_start`.

### The audit vocabulary gained one action

`evidence.preservation_request` · `targetType: 'preservation_request'` · `targetId` is the camera's
**external** id (`cam01`), matching D3-04's convention that `target_id` is text and addresses plates,
cameras and bundles alike. `params` carries `cameraId`, `cameraExternalId`, `windowStart`,
`windowEnd`, `retentionDaysAtRequest`, `expiresAtAtRequest`. Written by `writeAudit` **inside the
same transaction as the insert**, so either the request exists and the chain records who asked for it,
or neither happened.

### Numbers you can quote

| | |
|---|---|
| Sandbox estate declaring a retention period | **0 of 30** |
| Sandbox estate with coordinates | **0 of 30** (D1-08's finding, unchanged) |
| Retention buckets on the real estate | one: `null` × 30 |
| Default warning threshold | **48 h** (`RETENTION_EXPIRING_SOON_HOURS`) |
| Availability query, 35 cameras | **18–74 ms** end to end, measured on the page |
| Audit chain after this ticket's tests | **460 entries, 460 verified, 0 forks** |
| Tests added | **55** (21 shared clock · 25 API · 9 web presentation) |

### ⚠ For D4-04 / D4-05 — how to frame it

The ticket's own instruction, and it is right: **this is an investigation feature, not a storage
feature.** The slide is not "we track retention". It is:

> *An officer reports a snatching on day 12. Which of the cameras that covered that junction still
> hold the footage — and which department do they have to ring today, before tomorrow?*

Then the screenshot: five cameras, three retention regimes, two of them **expiring in 23 hours**, one
whose department never said. Then the honest half, which is the part that scores: SAAKSHI cannot stop
anybody's recorder. It can tell you the deadline, and it can make the request to beat it a matter of
record. `docs/retention-model.md` §6 and §7 are written for exactly that slide.

The second number for the deck: **0 of 30 cameras in the Gujarat catalogue declare a retention
period.** That is not our gap — it is the evidence that the question has no answer today.

### ⚠ For D3-GATE — reproducing the non-empty screenshot

The covering table is empty by construction on the real estate. To reproduce the deck screenshot,
seed placed cameras, then remove them:

```sql
insert into cameras (external_id, name, adapter_kind, retention_days, location, district) values
  ('D305DEMO-01','Paldi Circle (west approach)','hls',7,
   st_setsrid(st_makepoint(72.5661,23.0125),4326)::geography,'Ahmedabad'),
  ('D305DEMO-02','Paldi Circle (north approach)','hls',15,
   st_setsrid(st_makepoint(72.5669,23.0131),4326)::geography,'Ahmedabad'),
  ('D305DEMO-03','Bhatta Junction','hls',90,
   st_setsrid(st_makepoint(72.5682,23.0118),4326)::geography,'Ahmedabad'),
  ('D305DEMO-04','Paldi Char Rasta (AMC)','hls',null,
   st_setsrid(st_makepoint(72.5650,23.0119),4326)::geography,'Ahmedabad'),
  ('D305DEMO-05','Vasna Barrage Road','hls',7,
   st_setsrid(st_makepoint(72.5673,23.0140),4326)::geography,'Ahmedabad');
-- …screenshot…
delete from cameras where external_id like 'D305DEMO-%';
```

Then `/evidence?lat=23.0125&lon=72.5661&radius_m=500&at=<six days ago>`.

### ⚠ For D3-06 (gap analysis)

`cameras.retention_days` is `NULL` for the entire estate, so **retention cannot be a dimension of a
coverage-gap score computed today** — it would be one constant. It *is* worth naming as a gap in its
own right: "N cameras whose retention nobody has declared" is a finding with an owner and an action,
which is more than most gap metrics manage.

---

## Logged to BL-01

1. **The gate `curl` predates the RBAC matrix** (third occurrence — D1-06 and D1-GATE hit it first).
   Any future gate that `curl`s an endpoint literally will 401. Run it with a token and record the
   real output; never make a route public to satisfy a literal command.
2. **`maplibre-gl` and `@maplibre/maplibre-gl-style-spec` are empty directories in the shared
   checkout's `packages/web/node_modules`** — `npm ls maplibre-gl` reports `invalid`, and
   `npm run typecheck -w @saakshi/web` fails on `Cannot find module 'maplibre-gl'` for
   `registry-map.tsx` and `trace-map.tsx`. **Unrelated to this ticket** and reproducible before any
   of its changes. Worked around inside this worktree by extracting both tarballs from the npm cache
   into a real `packages/web/node_modules`; the shared checkout is untouched and still broken. A
   `npm install` on `main` should fix it, but somebody should confirm before D3-GATE runs a clean
   typecheck.
3. **Cross-worker Valkey contention, still live** (D3-01's finding #8): one full-suite run failed
   `consumers/evidence.test.ts` with `expected null not to be null` while another worker was active,
   and passed in isolation and on the immediate re-run. The `sightings` consumer group is shared
   across every worktree on this machine.
4. **`preservation_requests` has no status-transition route.** The queue can be created and read but
   not worked — `acknowledged` / `preserved` / `declined` are reachable only by SQL. Deliberately out
   of scope (the AC asks for "records … is audited … appears on the queue") and noted in
   `docs/retention-model.md` §7 as the step the department performs.
5. **`cameras.retention_days`, `location` and `department_id` are `NULL` for all 30 sandbox cameras.**
   Already known for `location` (D1-08); recording that retention and department are in the same
   state, because three features now depend on fields the catalogue does not publish.


---

### Manager note — merged as `dc8c517` (wave 0, batch 2)

Merged first in planner order. Migration `0020_preservation_requests` applies cleanly from scratch.

**Two later branches conflicted with this one in `server.ts` and both resolved additively** —
`registerRetentionRoutes` now registers alongside D3-10's metrics wrapper and D3-09's query routes.
The `expiringSoonHours:` options this ticket threaded into `registerAlertRoutes` / `registerTraceRoutes`
survived untouched.

**The measurement in this ticket is the deliverable, and it should reach the deck as such.**
0 of 30 sandbox cameras declare a retention period, none carry coordinates or a department, so the
estate answer is *0 covering / 30 unassessable, all `unknown`*. Rendering that in words rather than
as an empty table is the right call. D3-10 (#33) has since exported the same fact as
`saakshi_camera_retention_state` / `saakshi_estate_retention_cameras`, with `unknown` as its own
state rather than zero — the two now agree, and a judge can check either.

**`retention: null` is not `unknown`.** Null means "not computed on this delivery path" (live SSE);
`unknown` is an explicit state meaning the camera declares no retention. Any downstream zod parse
must use `AlertWithRetention`, because `z.object` strips unknown keys **silently**.

Repo-wide gate on `main` after the whole batch: typecheck ✅ · lint ✅ · format ✅ ·
**1175 TS tests passed / 15 skipped** · **218 pytest passed / 2 skipped** · `db:reset && db:migrate`
applies **19 migrations** cleanly from scratch.

**Comment by thopatevijay** [comment]
**Blocked by:** #10

Do not start this ticket until every blocker is closed. Verify with `/status` or `gh issue view <n>`.
